### ISSUE TITLE
如何实现小球不规则形变

### ISSUE THREAD

**Issue by McDo** [KittenYang/KYFloatingBubble#1]
hi, 非常感谢你提供的思路！仔细看了下Game Center小球的效果，是不规则形变的，我想实现思路可能是用bezier path画出四条弧线组成一个圆，然后通过Displaylink在每次屏幕刷新的时候，通过改变bezier path的control point来达到BIU~BIU~的效果的，不知道我理解的对不对，希望能得到您的指正。
如果这个思路是正确的话，那么怎么实现那种'easing'的效果的呢？需要在每个displayLinkWithTarget:selector: 中，怎样计算control points如何变化的呢？
非常非常想实现这个效果，可以为我提供一些实现思路吗？非常非常感谢你~

**Comment by KittenYang** [comment]
我一开始想实现这种融合的效果也是去算贝塞尔曲线的控制点坐标，但是displayLink的刷新频率和动画运动过程会出现时间差，所以不好看。后来，我发现了这个名词——“元球”。这里有Demo: [https://github.com/Dillion/VectorMetaballs](https://github.com/Dillion/VectorMetaballs)，你可以研究研究！

![default](https://cloud.githubusercontent.com/assets/5517281/7683790/f6d793f6-fdb3-11e4-8d48-de0ca95eb110.gif)

**Comment by McDo** [comment]
wow! 虽然看不太懂原理，但是如果让复制出来的圆绕着稍稍偏离一点的圆心移动就很有感觉了~ 谢谢！
